/**
 * Billing / Accounts Receivable routes (Phase 3), generated by the CRUD
 * factory. All five domains are org-scoped documents whose balances the
 * database computes (GENERATED columns), so the surface is plain CRUD with
 * server-assigned document numbers keyed to each document's own date.
 */
import {
  zBillingStatementInput,
  zBillingStatementUpdate,
  zServiceInvoiceInput,
  zServiceInvoiceUpdate,
  zCollectionInput,
  zCollectionUpdate,
  zPaymentScheduleInput,
  zPaymentScheduleUpdate,
  zSchedulePaymentInput,
  zSchedulePaymentUpdate,
} from "@sentire-books/domain";
import {
  billingStatements,
  serviceInvoices,
  collections,
  paymentSchedules,
  schedulePayments,
} from "@sentire-books/db";
import { makeCrudRoutes } from "./crudFactory";

export const billingStatementRoutes = makeCrudRoutes({
  plural: "statements",
  singular: "statement",
  table: billingStatements,
  createSchema: zBillingStatementInput,
  updateSchema: zBillingStatementUpdate,
  orderBy: [{ column: billingStatements.createdAt, dir: "desc" }],
  docNo: { field: "bsNo", prefix: "BS", dateField: "billingDate" },
});

export const serviceInvoiceRoutes = makeCrudRoutes({
  plural: "invoices",
  singular: "invoice",
  table: serviceInvoices,
  createSchema: zServiceInvoiceInput,
  updateSchema: zServiceInvoiceUpdate,
  orderBy: [{ column: serviceInvoices.createdAt, dir: "desc" }],
  docNo: { field: "siNo", prefix: "IS", dateField: "siDate" },
});

export const collectionRoutes = makeCrudRoutes({
  plural: "collections",
  singular: "collection",
  table: collections,
  createSchema: zCollectionInput,
  updateSchema: zCollectionUpdate,
  orderBy: [{ column: collections.createdAt, dir: "desc" }],
  docNo: { field: "collectionNo", prefix: "COL", dateField: "collectionDate" },
});

export const paymentScheduleRoutes = makeCrudRoutes({
  plural: "schedules",
  singular: "schedule",
  table: paymentSchedules,
  createSchema: zPaymentScheduleInput,
  updateSchema: zPaymentScheduleUpdate,
  orderBy: [{ column: paymentSchedules.createdAt, dir: "desc" }],
  docNo: { field: "scheduleNo", prefix: "PS", dateField: "startDate" },
});

export const schedulePaymentRoutes = makeCrudRoutes({
  plural: "payments",
  singular: "payment",
  table: schedulePayments,
  createSchema: zSchedulePaymentInput,
  updateSchema: zSchedulePaymentUpdate,
  orderBy: [{ column: schedulePayments.createdAt, dir: "desc" }],
});
