// ════════════════════════════════════════════════════════════════════════════
// GENERATED — do not edit by hand. Regenerate with setup/generate_coa_sql.py.
// The default Chart of Accounts the software provisions for every organization.
// 158 accounts. `code` is a display label (it repeats across types);
// the unique key is `name`. Parents are referenced by `parentName`.
// ════════════════════════════════════════════════════════════════════════════
import type { ChartAccount } from "./accounts";

export const DEFAULT_CHART_OF_ACCOUNTS: readonly ChartAccount[] = [
  { code: "1002", name: "Advances to Emp and Officers", type: "asset", normalBalance: "debit", subtype: "Other Current Asset" },
  { code: "1003", name: "Property, plant and equipment", type: "asset", normalBalance: "debit", subtype: "Fixed Asset", description: "Purchases of furniture and equipment for your office that can be used for a long period of time usually exceeding one year can be tracked with this account." },
  { code: "1001022", name: "Trade Receivable - Client", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable" },
  { code: "1001640", name: "Cash in Bank - UB Savings", type: "asset", normalBalance: "debit", subtype: "Bank" },
  { code: "1002001", name: "Petty Cash", type: "asset", normalBalance: "debit", subtype: "Cash Equivalents", description: "It is a small amount of cash that is used to pay your minor or casual expenses rather than writing a check." },
  { code: "1002002", name: "Accounts Receivable from Employees", type: "asset", normalBalance: "debit", subtype: "Other Current Asset", description: "Money paid out to an employee in advance can be tracked here till it's repaid or shown to be spent for company purposes.", parentName: "Advances to Emp and Officers" },
  { code: "1002003", name: "Accounts Receivable from Officers", type: "asset", normalBalance: "debit", subtype: "Other Current Asset", parentName: "Advances to Emp and Officers" },
  { code: "1002004", name: "Undeposited Funds", type: "asset", normalBalance: "debit", subtype: "Cash Equivalents", description: "Record funds received by your company yet to be deposited in a bank as undeposited funds and group them as a current asset in your balance sheet." },
  { code: "1002005", name: "Revolving Fund - Employees", type: "asset", normalBalance: "debit", subtype: "Cash Equivalents", description: "Revolving fund for employees" },
  { code: "1002184", name: "Cash in Bank - BPI Checking", type: "asset", normalBalance: "debit", subtype: "Bank" },
  { code: "1003001", name: "Work Equipments", type: "asset", normalBalance: "debit", subtype: "Fixed Asset", parentName: "Property, plant and equipment" },
  { code: "1003002", name: "Automobile", type: "asset", normalBalance: "debit", subtype: "Fixed Asset", parentName: "Property, plant and equipment" },
  { code: "1003003", name: "Furnitures and Fixtures", type: "asset", normalBalance: "debit", subtype: "Fixed Asset", parentName: "Property, plant and equipment" },
  { code: "9003001", name: "Accumulated Depreciation", type: "asset", normalBalance: "debit", subtype: "Fixed Asset", parentName: "Property, plant and equipment" },
  { code: "1004001", name: "Prepaid Expenses", type: "asset", normalBalance: "debit", subtype: "Other Current Asset", description: "An asset account that reports amounts paid in advance while purchasing goods or services from a vendor." },
  { code: "1004489", name: "Cash in Bank - BDO Savings", type: "asset", normalBalance: "debit", subtype: "Bank", description: "BDO Savings Account" },
  { code: "1007923", name: "Cash in Bank - RCBC Checking", type: "asset", normalBalance: "debit", subtype: "Bank" },
  { code: "1008317", name: "Cash in Bank - Security Bank Checking", type: "asset", normalBalance: "debit", subtype: "Bank" },
  { code: "1008928", name: "Cash in Bank - UB Checking", type: "asset", normalBalance: "debit", subtype: "Bank", description: "UB Business Checking" },
  { code: "1009001", name: "Deferred Tax Asset", type: "asset", normalBalance: "debit", subtype: "Tax Asset", description: "Any tax which is paid in advance is recorded into the advance tax account. This advance tax payment could be a quarterly, half yearly or yearly payment." },
  { code: "1009336", name: "Cash in Bank - BPI KCL", type: "asset", normalBalance: "debit", subtype: "Bank" },
  { code: "8000001", name: "Input Tax", type: "asset", normalBalance: "debit", subtype: "Tax Asset", description: "The amount of money charged to you as Tax on your purchases." },
  { code: "DO101", name: "TR - SPX - Province", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", parentName: "Trade Receivable - Client" },
  { code: "DO102", name: "TR - SPX NCR+", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", parentName: "Trade Receivable - Client" },
  { code: "DO103", name: "Iontech Enterprises Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", parentName: "Trade Receivable - Client" },
  { code: "DO104", name: "Docquity Philippines Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Docquity Philippines Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO105", name: "1Life Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "1Life Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO106", name: "TR - Accupoint Systems Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Accupoint Systems Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO107", name: "TR - Adele Fado Trading Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Adele Fado Trading Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO108", name: "TR - ALaundry Comp Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "ALaundry Comp Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO109", name: "Allegiance Insurance Agency Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Allegiance Insurance Agency Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO110", name: "Zenorex Marketing Corporation", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Zenorex Marketing Corporation", parentName: "Trade Receivable - Client" },
  { code: "DO111", name: "TR - Beyond Innovation (BEY)", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Beyond Innovation", parentName: "Trade Receivable - Client" },
  { code: "DO112", name: "Boxtalks Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Boxtalks Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO113", name: "TR - Cosmos Bazar Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Cosmos Bazar Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO114", name: "TR - Digits Trading Corp", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Digits Trading Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO115", name: "DGNation Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "DGNation Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO116", name: "Digital Walker Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Digital Walker Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO117", name: "Digitalks Technology Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Digitalks Technology Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO118", name: "TR - Environmental-Health Laboratory Services Cooperative", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Environmental-Health Laboratory Services Cooperative", parentName: "Trade Receivable - Client" },
  { code: "DO119", name: "TR - F2 Logistics", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "F2 Logistics Philippines, Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO120", name: "TR - F2 - LAGUNA", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "F2 Logistics Philippines, Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO121", name: "Great Deals E Commerce Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Great Deals E Commerce Corp.", parentName: "Trade Receivable - Client" },
  { code: "DO122", name: "iClick Digishop Corp", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "iClick Digishop Corp", parentName: "Trade Receivable - Client" },
  { code: "DO123", name: "Index 94 Lifestyle Solutions Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Index 94 Lifestyle Solutions Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO124", name: "TR - J&R Appliances", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "J&R Appliances", parentName: "Trade Receivable - Client" },
  { code: "DO125", name: "JW Summit Group Inc.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "JW Summit Group Inc.", parentName: "Trade Receivable - Client" },
  { code: "DO126", name: "TR - Wise Corp.", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Wavelength Imaging Solutions Expert Corporation", parentName: "Trade Receivable - Client" },
  { code: "DO127", name: "Upson Global", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Upson Global", parentName: "Trade Receivable - Client" },
  { code: "DO128", name: "TR - Sokany Trading Corp", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Upson Global", parentName: "Trade Receivable - Client" },
  { code: "DO129", name: "TR - Sokany Trading Corp Warehouse", type: "asset", normalBalance: "debit", subtype: "Accounts Receivable", description: "Upson Global", parentName: "Trade Receivable - Client" },
  { code: "4002", name: "Cost of Services", type: "expense", normalBalance: "debit", subtype: "Cost of Services", description: "An expense account which tracks the value of the services sold." },
  { code: "4001001", name: "Salaries and Wages Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", description: "Client Billings for remittance to Social Agencies", parentName: "Cost of Services" },
  { code: "4001002", name: "Accrued 13th Month Pay Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "4001003", name: "Recruitment Cost", type: "expense", normalBalance: "debit", subtype: "Cost of Services", description: "Recruitment Cost for mass hiring and job postings", parentName: "Cost of Services" },
  { code: "4002001", name: "SSS ER Share Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "4002002", name: "HDMF ER Share Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "4002003", name: "PHIC ER Share Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "4002004", name: "Employee Incentives Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "4002005", name: "Employee Allowances Deployed", type: "expense", normalBalance: "debit", subtype: "Cost of Services", parentName: "Cost of Services" },
  { code: "2004001", name: "Owner's Equity", type: "equity", normalBalance: "credit", subtype: "Equity", description: "The owners rights to the assets of a company can be quantified in the owner''s equity account." },
  { code: "2004002", name: "Opening Balance Offset", type: "equity", normalBalance: "credit", subtype: "Equity", description: "This is an account where you can record the balance from your previous years earning or the amount set aside for some activities. It is like a buffer account for your funds." },
  { code: "2004003", name: "Retained Earnings", type: "equity", normalBalance: "credit", subtype: "Equity", description: "The earnings of your company which are not distributed among the share holders is accounted as retained earnings." },
  { code: "5001", name: "Personnel Cost", type: "expense", normalBalance: "debit", subtype: "Personnel Cost" },
  { code: "5002", name: "General and Administrative Expenses", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses" },
  { code: "5003", name: "Utilities", type: "expense", normalBalance: "debit", subtype: "Utilities" },
  { code: "5004", name: "Finance Cost and Amortization", type: "expense", normalBalance: "debit", subtype: "Finance Cost and Amortization" },
  { code: "5005", name: "Taxes and Licenses", type: "expense", normalBalance: "debit", subtype: "Taxes and Licenses" },
  { code: "5001001", name: "Salaries and Wages", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001002", name: "Overtime Pay", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001003", name: "13th Month Pay", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001004", name: "Personnel Allowance", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001005", name: "Clothing Allowance", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001006", name: "SSS Premium ER Share", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001007", name: "HDMF Premium ER Share", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001008", name: "PHIC Premium ER Share", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001009", name: "HMO Benefits", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001010", name: "STIP - Employees", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001011", name: "STIP - Officers", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001012", name: "Last Pay to Employees", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001013", name: "Insurance - Disability", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001014", name: "Insurance - Liability", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001015", name: "Insurance - General", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001016", name: "Management compensation", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5001017", name: "Accrued Medical Exam for Employees", type: "expense", normalBalance: "debit", subtype: "Personnel Cost", parentName: "Personnel Cost" },
  { code: "5002001", name: "Advertising and Promotion", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002002", name: "Fuel and Oil", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002003", name: "Miscellaneous", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002004", name: "Office Supplies", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002005", name: "Repairs and Maintenance - Materials/Supplies", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002006", name: "Representation and Entertainment", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002007", name: "Meals and Transportation", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002008", name: "Gatherings and Teambuildings", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002009", name: "Dues and subscriptions", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002010", name: "Equipment Rental", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002011", name: "Checkbook Reorder", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002012", name: "Training and Development", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002013", name: "Professional Services", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002014", name: "Interest Expense", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002015", name: "Shipping and Delivery Expense", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002016", name: "Rental HO", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002017", name: "Rental Branch", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", parentName: "General and Administrative Expenses" },
  { code: "5002018", name: "Lodging", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", description: "Any expense related to putting up at motels etc while on business travel can be entered here.", parentName: "General and Administrative Expenses" },
  { code: "5002019", name: "Other Selling Expenses", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", description: "Any minor expense on activities unrelated to primary business operations is recorded under the other expense account.", parentName: "General and Administrative Expenses" },
  { code: "5002020", name: "Credit Card Charges", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", description: "Service fees for transactions , balance transfer fees, annual credit fees and other charges levied on a credit card are recorded into the credit card account.", parentName: "General and Administrative Expenses" },
  { code: "5002021", name: "Bank Fees and Charges", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses", description: "Any bank fees levied is recorded into the bank fees and charges account. A bank account maintenance fee, transaction charges, a late payment fee are some examples." },
  { code: "5002022", name: "Other general and administrative expenses", type: "expense", normalBalance: "debit", subtype: "General and Administrative Expenses" },
  { code: "5003001", name: "Electricity", type: "expense", normalBalance: "debit", subtype: "Utilities", parentName: "Utilities" },
  { code: "5003002", name: "Communication", type: "expense", normalBalance: "debit", subtype: "Utilities", parentName: "Utilities" },
  { code: "5003003", name: "Water", type: "expense", normalBalance: "debit", subtype: "Utilities", parentName: "Utilities" },
  { code: "5004001", name: "Finance Cost", type: "expense", normalBalance: "debit", subtype: "Finance Cost and Amortization", parentName: "Finance Cost and Amortization" },
  { code: "5004002", name: "Amortization", type: "expense", normalBalance: "debit", subtype: "Finance Cost and Amortization", parentName: "Finance Cost and Amortization" },
  { code: "5004003", name: "Bad Debt", type: "expense", normalBalance: "debit", subtype: "Non Cash Expenses", description: "Any amount which is lost and is unrecoverable is recorded into the bad debt account." },
  { code: "5004004", name: "Depreciation Expense", type: "expense", normalBalance: "debit", subtype: "Non Cash Expenses", description: "Any depreciation in value of your assets can be captured as a depreciation expense." },
  { code: "5005001", name: "Business and Income Tax", type: "expense", normalBalance: "debit", subtype: "Taxes and Licenses", parentName: "Taxes and Licenses" },
  { code: "5005002", name: "Business Licenses and Permits", type: "expense", normalBalance: "debit", subtype: "Taxes and Licenses", parentName: "Taxes and Licenses" },
  { code: "5006001", name: "Exchange Gain or Loss", type: "expense", normalBalance: "debit", subtype: "Other Expense", description: "Changing the conversion rate can result in a gain or a loss. You can record this into the exchange gain or loss account." },
  { code: "5900000", name: "Other General Expenses", type: "expense", normalBalance: "debit", subtype: "Other General Expenses" },
  { code: "3001001", name: "Manpower Service Revenue", type: "income", normalBalance: "credit", subtype: "Income", description: "The income from the sales in your business is recorded under the sales account." },
  { code: "3001002", name: "SaaS Revenue", type: "income", normalBalance: "credit", subtype: "Income" },
  { code: "3001003", name: "Placement Service Revenue", type: "income", normalBalance: "credit", subtype: "Income", description: "Headhunting / Placement Services" },
  { code: "3001004", name: "Billable Expense Income", type: "income", normalBalance: "credit", subtype: "Income", description: "Charges to clients (SSS, Philhealth, Pagibig and other Allowances)" },
  { code: "3001005", name: "Bank Fees Recovered", type: "income", normalBalance: "credit", subtype: "Income", description: "Bank Fees charged to employees without Payroll bank account" },
  { code: "3001006", name: "Other Services Revenue", type: "income", normalBalance: "credit", subtype: "Other Income" },
  { code: "3001007", name: "Interest Income", type: "income", normalBalance: "credit", subtype: "Other Income", description: "A percentage of your balances and deposits are given as interest to you by your banks and financial institutions. This interest is recorded into the interest income account." },
  { code: "3901001", name: "Discount", type: "income", normalBalance: "credit", subtype: "Income", description: "Any reduction on your selling price as a discount can be recorded into the discount account." },
  { code: "2001", name: "Short Term Debt", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2002", name: "Accounts Payable to Emp and Officers", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2003", name: "Tax Payable", type: "liability", normalBalance: "credit", subtype: "Tax Liability", description: "The amount of money which you owe to your tax authority is recorded under the tax payable account. This amount is a sum of your outstanding in taxes and the tax charged on sales." },
  { code: "2008", name: "Social Agency Contribution Payable", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2009", name: "Employee Benefit Claims Payable", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2101", name: "Expanded Withholding Tax Payable", type: "liability", normalBalance: "credit", subtype: "Tax Liability" },
  { code: "2001001", name: "Accounts Payable", type: "liability", normalBalance: "credit", subtype: "Accounts Payable", description: "This is an account of all the money which you owe to others like a pending bill payment to a vendor,etc.", parentName: "Short Term Debt" },
  { code: "2001002", name: "Loans Payable", type: "liability", normalBalance: "credit", subtype: "Accounts Payable", description: "This is an account of all the money which you owe to others like a pending bill payment to a vendor,etc.", parentName: "Short Term Debt" },
  { code: "2001003", name: "Fixed Assets Payable", type: "liability", normalBalance: "credit", subtype: "Accounts Payable", description: "This is an account of installment clearing account of Fixed Assets", parentName: "Short Term Debt" },
  { code: "2002001", name: "Employee Reimbursements", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", description: "This account can be used to track the reimbursements that are due to be paid out to employees.", parentName: "Accounts Payable to Emp and Officers" },
  { code: "2002002", name: "Accounts Payable to Shareholders", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Accounts Payable to Emp and Officers" },
  { code: "2003001", name: "Deferred Tax Liability", type: "liability", normalBalance: "credit", subtype: "Tax Liability" },
  { code: "2003002", name: "Income Tax Payable", type: "liability", normalBalance: "credit", subtype: "Tax Liability" },
  { code: "2003003", name: "Output Tax", type: "liability", normalBalance: "credit", subtype: "Tax Liability", description: "The amount of money charged as Tax on your sales." },
  { code: "2004001", name: "Salaries and Wages Payable", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2004002", name: "Final Pay Payable Deployed", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2004003", name: "Final Pay Payable", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
  { code: "2008001", name: "SSS EmployER Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2008002", name: "HDMF EmployER Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2008003", name: "PHIC EmployER Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2008004", name: "SSS EmployEE Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2008005", name: "HDMF EmployEE Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2008006", name: "PHIC EmployEE Contribution", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Social Agency Contribution Payable" },
  { code: "2009001", name: "SSS Employee Loans and Benefits", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Employee Benefit Claims Payable" },
  { code: "2009002", name: "HDMF Employee Loans and Benefits", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Employee Benefit Claims Payable" },
  { code: "2009003", name: "13th Month Payable", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", parentName: "Employee Benefit Claims Payable" },
  { code: "2101001", name: "Withholding Tax on Compensation Payable", type: "liability", normalBalance: "credit", subtype: "Tax Liability", parentName: "Expanded Withholding Tax Payable" },
  { code: "2101002", name: "EWT Vendors", type: "liability", normalBalance: "credit", subtype: "Tax Liability", parentName: "Expanded Withholding Tax Payable" },
  { code: "2101003", name: "Final Withholding Tax Payable", type: "liability", normalBalance: "credit", subtype: "Tax Liability", parentName: "Expanded Withholding Tax Payable" },
  { code: "2600001", name: "Unearned Revenue", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", description: "A liability account that reports amounts received in advance of providing goods or services. When the goods or services are provided, this account balance is decreased and a revenue account is increased." },
  { code: "2700001", name: "Opening Balance Adjustments", type: "liability", normalBalance: "credit", subtype: "Other Current Liability", description: "This account will hold the difference in the debits and credits entered during the opening balance." },
  { code: "2800001", name: "Post-Dated Checks Issued", type: "liability", normalBalance: "credit", subtype: "Other Current Liability" },
];
