/**
 * Tax subsystem + Bank management routes (Phases 4-5), generated by the CRUD
 * factory. Tax config is admin-write (it drives JE tax postings); bank records
 * are open to members.
 */
import {
  zTaxRateInput,
  zTaxRateUpdate,
  zTaxGroupInput,
  zTaxGroupUpdate,
  zPurposeCategoryInput,
  zPurposeCategoryUpdate,
  zBankBalanceInput,
  zBankBalanceUpdate,
  zBankTransactionInput,
  zBankTransactionUpdate,
  zBankReconciliationInput,
  zBankReconciliationUpdate,
} from "@scalebooks/domain";
import {
  taxRates,
  taxGroups,
  purposeCategories,
  dailyBankBalances,
  bankTransactions,
  bankReconciliations,
} from "@scalebooks/db";
import { makeCrudRoutes } from "./crudFactory";

export const taxRateRoutes = makeCrudRoutes({
  plural: "rates",
  singular: "rate",
  table: taxRates,
  createSchema: zTaxRateInput,
  updateSchema: zTaxRateUpdate,
  orderBy: [{ column: taxRates.name, dir: "asc" }],
  adminWrites: true,
});

export const taxGroupRoutes = makeCrudRoutes({
  plural: "groups",
  singular: "group",
  table: taxGroups,
  createSchema: zTaxGroupInput,
  updateSchema: zTaxGroupUpdate,
  orderBy: [{ column: taxGroups.name, dir: "asc" }],
  adminWrites: true,
});

export const purposeCategoryRoutes = makeCrudRoutes({
  plural: "categories",
  singular: "category",
  table: purposeCategories,
  createSchema: zPurposeCategoryInput,
  updateSchema: zPurposeCategoryUpdate,
  orderBy: [{ column: purposeCategories.name, dir: "asc" }],
  stampCreatedBy: false,
});

export const bankBalanceRoutes = makeCrudRoutes({
  plural: "balances",
  singular: "balance",
  table: dailyBankBalances,
  createSchema: zBankBalanceInput,
  updateSchema: zBankBalanceUpdate,
  orderBy: [{ column: dailyBankBalances.balanceDate, dir: "desc" }],
});

export const bankTransactionRoutes = makeCrudRoutes({
  plural: "transactions",
  singular: "transaction",
  table: bankTransactions,
  createSchema: zBankTransactionInput,
  updateSchema: zBankTransactionUpdate,
  orderBy: [{ column: bankTransactions.txDate, dir: "desc" }],
});

export const bankReconciliationRoutes = makeCrudRoutes({
  plural: "reconciliations",
  singular: "reconciliation",
  table: bankReconciliations,
  createSchema: zBankReconciliationInput,
  updateSchema: zBankReconciliationUpdate,
  orderBy: [{ column: bankReconciliations.createdAt, dir: "desc" }],
  docNo: { field: "reconNo", prefix: "RC" },
});
